### ISSUE TITLE
Building the FFmpeg meet ERROR: opengl not found.

### ISSUE THREAD

**Issue by moonshoter** [nervous-systems/ffmpeg-opengl#1]
Hi,I try to build ffmpeg with your opengl filter for android but  meet some trouble.ERROR: opengl not found.

`BEGIN /tmp/ffconf.dHKcaBnS.c
    1	#include <ES2/gl.h>
    2	#include <stdint.h>
    3	long check_glGetError(void) { return (long) glGetError; }
    4	int main(void) { int ret = 0;
    5	 ret |= ((intptr_t)check_glGetError) & 0xFFFF;
    6	return ret; }
END /tmp/ffconf.dHKcaBnS.c
/Users/liyaochi/develop/android-ndk-r14b/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64/bin/arm-linux-androideabi-gcc --sysroot=/Users/liyaochi/develop/android-ndk-r14b/platforms/android-23/arch-arm/ -isysroot /Users/liyaochi/develop/android-ndk-r14b/platforms/android-23/arch-arm/ -D_ISOC99_SOURCE -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -Dstrtod=avpriv_strtod -DPIC -Os -fpic -marm -march=armv5te -std=c11 -fomit-frame-pointer -fPIC -marm -pthread -isysroot=/Users/liyaochi/develop/android-ndk-r14b/platforms/android-23/arch-arm/ -Wl,-framework,OpenGLES -c -o /tmp/ffconf.e3HyUoXk.o /tmp/ffconf.dHKcaBnS.c
/tmp/ffconf.dHKcaBnS.c:1:20: fatal error: ES2/gl.h: No such file or directory
 #include <ES2/gl.h>
                    ^
compilation terminated.
ERROR: opengl not found.`

And there is my shell scipt
`#!/bin/bash
export NDK=/Users/liyaochi/develop/android-ndk-r14b
export SYSROOT=$NDK/platforms/android-23/arch-arm/
export TOOLCHAIN=$NDK/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64
function build_one
{
./configure \
    --prefix=$PREFIX \
    --enable-shared \
    --disable-static \
    --disable-doc \
    --disable-ffmpeg \
    --disable-ffplay \
    --disable-ffprobe \
    --disable-ffserver \
    --disable-avdevice \
    --disable-doc \
    --target-os=android \
    --disable-symver \
    --cross-prefix=$TOOLCHAIN/bin/arm-linux-androideabi- \
    --arch=arm \
    --enable-cross-compile \
    --enable-filter=genericshader \
    --enable-gpl \
    --enable-opengl \
    --extra-libs='-glfw3' \
    --sysroot=$SYSROOT \
    --extra-cflags="-Os -fpic -framework OpenGL -framework GLUT $ADDI_CFLAGS" \
    --extra-ldflags="$ADDI_LDFLAGS" \
    $ADDITIONAL_CONFIGURE_FLAG
make clean
make
make install
}
CPU=arm
PREFIX=$(pwd)/android/$CPU 
ADDI_CFLAGS="-marm"
build_one`

**Comment by moonshoter** [comment]
can your share the build script in linux ？I try to build but failue.

**Comment by moea** [comment]
@moonshoter You're trying to build a Linux binary on Linux?  I can help with that, but I wouldn't really know what to suggest if you're building an Android binary from Linux - I've built ffmpeg for Android before, but not with opengl support.

The `Building` section of the README should be a decent starting point for building a Linux binary.

**Comment by moonshoter** [comment]
I try to build in linux first,and then try to build for android.
And I deal the problem.But I used android ndk to build meet some undefined reference to error about glew and glfw. I guese It's because ndk gcc can't  link the libs. but I had add `-L/{$LIBPATH}`.
I thinks It is posiable to write the shader.c use GLES ??

**Comment by moea** [comment]
@moonshoter Yeah, it would be relatively easy to run it under GLES, but depending on the Android support for glew and glfw, you may want to consider rewriting the plugin to remove those dependencies.  My intuition tells me that the performance wouldn't be great compared to using the accelerated/high-level surface based API, either directly, or via something like [media for mobile](https://github.com/INDExOS/media-for-mobile)
