### ISSUE TITLE
question: windows

### ISSUE THREAD

**Issue by m-ziglioli** [nervous-systems/ffmpeg-opengl#8]
can this be done on windows?

**Comment by numberwolf** [comment]
on windows, you can use : https://github.com/numberwolf/FFmpeg-Plus-OpenGL

**Comment by m-ziglioli** [comment]
thanks, i'll check later

**Comment by feanor3** [comment]
I'm not an expert: may you help me? I'm running ubuntu via microsoft store application, i've installed packages but when doing git  apply I get:
error: patch failed: libavfilter/allfilters.c:444
error: libavfilter/allfilters.c: patch does not apply

**Comment by m-ziglioli** [comment]
May you help me? when trying encoding I get 
```gcc is unable to create an executable file.

C compiler test failed.
```

and if I check ffmpeg/ffbuild/config.log in the last lines there is 
```
BEGIN /tmp/ffconf.pdumaQBS/test.c

    1	int main(void){ return 0; }

END /tmp/ffconf.pdumaQBS/test.c

gcc -c -o /tmp/ffconf.pdumaQBS/test.o /tmp/ffconf.pdumaQBS/test.c

gcc -lm -lz -llzma -lpthread -o /tmp/ffconf.pdumaQBS/test /tmp/ffconf.pdumaQBS/test.o -lGLEW -lglfw -lm -lpthread

/usr/bin/ld: cannot find -llzma

collect2: error: ld returned 1 exit status

C compiler test failed.
```

**Comment by numberwolf** [comment]
> May you help me? when trying encoding I get
> 
> ```
> 
> C compiler test failed.
> ```
> 
> and if I check ffmpeg/ffbuild/config.log in the last lines there is
> 
> ```
> BEGIN /tmp/ffconf.pdumaQBS/test.c
> 
>     1	int main(void){ return 0; }
> 
> END /tmp/ffconf.pdumaQBS/test.c
> 
> gcc -c -o /tmp/ffconf.pdumaQBS/test.o /tmp/ffconf.pdumaQBS/test.c
> 
> gcc -lm -lz -llzma -lpthread -o /tmp/ffconf.pdumaQBS/test /tmp/ffconf.pdumaQBS/test.o -lGLEW -lglfw -lm -lpthread
> 
> /usr/bin/ld: cannot find -llzma
> 
> collect2: error: ld returned 1 exit status
> 
> C compiler test failed.
> ```

you need to install lzma, 

yum install lzma

**Comment by m-ziglioli** [comment]
Thank you. Compiling I get another error:
```
libavfilter/vf_lutglshader.c: At top level:

libavfilter/vf_lutglshader.c:1028:6: error: ‘AVFilter’ has no member named ‘query_formats’

 1028 |     .query_formats = query_formats,
```

**Comment by moea** [comment]
This is because you're using a much more recent version of ffmpeg than this
was written against.  I haven't maintained it.

**Comment by numberwolf** [comment]
> Thank you. Compiling I get another error:
> 
> ```
> libavfilter/vf_lutglshader.c: At top level:
> 
> libavfilter/vf_lutglshader.c:1028:6: error: ‘AVFilter’ has no member named ‘query_formats’
> 
>  1028 |     .query_formats = query_formats,
> ```

Use the ffmpeg which version in 4.3 4.2 4.1

**Comment by m-ziglioli** [comment]
Thanks you both.
